services:
  db:
    build: .
    environment:
      POSTGRES_DB: b2b_proyecto
      POSTGRES_USER: "owner"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./start-scripts/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
      - ./start-scripts/quartz.sql:/docker-entrypoint-initdb.d/quartz.sql
    container_name: b2b_database
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U owner -d b2b_proyecto"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    restart: unless-stopped
    environment:
      # Datasource
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/b2b_proyecto
      SPRING_DATASOURCE_USERNAME: owner
      SPRING_DATASOURCE_PASSWORD: "123456"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      # JWT
      SECURITY_JWT_TOKEN_SECRET_KEY: pQKOkAZ8j59Kb6QJC+LHL7viCOUvfhBZ7PjGeIznKbY=
      SECURITY_JWT_TOKEN_EXPIRE_LENGTH: 200
      # TOTP
      TOTP_ENCRYPTION_PASSWORD: B2BSecretTotp2024!
      # Stereum
      STEREUM_API_URL: https://api.stereum.tech
      STEREUM_API_KEY: 75cc405e-ae77-42dd-a695-3cff98232266
      STEREUM_ACCOUNT_ID: 73133c83-e0f0-48ba-8360-4e1ddbf38495
      STEREUM_SECRET_KEY: 7144779d3dec4ec2855ef52cf405a5ab6ef42ab1b065445ab61e025b57f10dcd6fcda27c775a4a5797b99913d451c2b0863d8de5bc3549d790f503f457b1ea1e
      # Async
      ASYNC_CORE_POOL_SIZE: 5
      ASYNC_MAX_POOL_SIZQE: 10
      ASYNC_QUEUE_CAPACITY: 20
      # Actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      # Mail (set real values or remove if not used in prod)
      MAIL_HOST: smtp.gmail.com
      MAIL_SMTP_PORT: 587
      MAIL_SMTP_AUTH: "true"
      MAIL_SMTP_STARTTLS_ENABLE: "true"
      MAIL_SMTP_PROTOCOL: smtp
      MAIL_SMTP_USERNAME: rodriguezsanizofernando@gmail.com
      MAIL_SMTP_PASSWORD: mcjaujmuwvrajtlh
      MAIL_SMTP_FROM_MAIL: rodriguezsanizofernando@gmail.com
      MAIL_SMTP_MAIL_NOREPLY: rodriguezsanizofernando@gmail.com
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
